version: '3'
services:
  
  app_php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-todo
    container_name: app_php
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/.env.example:/var/www/html/.env

  webserver:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_php
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel-long
      MYSQL_DATABASE: training-laravel
      MYSQL_USER: laravel-long
      MYSQL_PASSWORD: laravel-long
      